# Generated by Django 4.0.5 on 2022-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appdetail_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
