# Generated by Django 4.0.5 on 2022-07-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='last_worker_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='scrcpy_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='worker_uuid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='APPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('data', models.CharField(max_length=40000)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appdetail')),
            ],
        ),
    ]
