# Generated by Django 4.0.5 on 2022-07-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appdetail_last_worker_time_appdetail_scrcpy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='job_alive_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='job_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='uuid',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
