# Generated by Django 4.0.5 on 2022-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_applog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
