# Generated by Django 4.0.5 on 2022-08-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appdetail_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='app_displayname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
