# Generated by Django 4.0.5 on 2022-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_appdetail_app_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='hook_feature',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
