# Generated by Django 4.0.5 on 2022-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_appscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='uuid',
            field=models.CharField(max_length=40),
        ),
    ]
