# Generated by Django 4.0.5 on 2022-08-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_appdetail_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='status_msg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
