# Generated by Django 4.0.5 on 2022-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_appdetail_status_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetail',
            name='androidversion_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
